-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_IFFT_no_scale\t\dataMEM_re_0_2_4x18b.vhd
-- Created: 2018-01-25 18:20:51
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: dataMEM_re_0_2_4x18b
-- Source Path: t/IFFT/IFFT HDL Optimized/RADIX22FFT_SDF2_2/dataMEM_re_0_2_4x18b
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY dataMEM_re_0_2_4x18b IS
  PORT( clk                               :   IN    std_logic;
        wr_din                            :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
        wr_addr                           :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        wr_en                             :   IN    std_logic;  -- ufix1
        rd_addr                           :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        rd_dout                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
        );
END dataMEM_re_0_2_4x18b;


ARCHITECTURE rtl OF dataMEM_re_0_2_4x18b IS

  -- Component Declarations
  COMPONENT SimpleDualPortRAM_4x18b
    PORT( clk                             :   IN    std_logic;
          wr_din                          :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En15
          wr_addr                         :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          wr_en                           :   IN    std_logic;  -- ufix1
          rd_addr                         :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          rd_dout                         :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En15
          );
  END COMPONENT;

  -- Signals
  SIGNAL rd_dout_tmp                      : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_SimpleDualPortRAM_4x18b : SimpleDualPortRAM_4x18b
    PORT MAP( clk => clk,
              wr_din => wr_din,  -- sfix18_En15
              wr_addr => wr_addr,  -- ufix2
              wr_en => wr_en,  -- ufix1
              rd_addr => rd_addr,  -- ufix2
              rd_dout => rd_dout_tmp  -- sfix18_En15
              );

  rd_dout <= rd_dout_tmp;

END rtl;

