-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_IFFT_no_scale\t\IFFT.vhd
-- Created: 2018-01-25 18:20:51
-- 
-- Generated by MATLAB 9.0 and HDL Coder 3.8
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0625
-- Target subsystem base rate: 0.0625
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: IFFT
-- Source Path: t/IFFT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY IFFT IS
  PORT( clk                               :   IN    std_logic;
        ce                                :   IN    std_logic;
        reset                             :   IN    std_logic;
        data_re                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        data_im                           :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        valid                             :   IN    std_logic;
        data_out_re                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En15
        data_out_im                       :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En15
        valid_out                         :   OUT   std_logic
        );
END IFFT;


ARCHITECTURE rtl OF IFFT IS

  -- Component Declarations
  COMPONENT IFFT_HDL_Optimized
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          dataIn_im                       :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
          validIn                         :   IN    std_logic;
          softReset                       :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En15
          dataOut_im                      :   OUT   std_logic_vector(19 DOWNTO 0);  -- sfix20_En15
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  -- Signals
  SIGNAL IFFT_HDL_Optimized_out1_re       : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL IFFT_HDL_Optimized_out1_im       : std_logic_vector(19 DOWNTO 0);  -- ufix20
  SIGNAL IFFT_HDL_Optimized_out2          : std_logic;

BEGIN
  u_IFFT_HDL_Optimized : IFFT_HDL_Optimized
    PORT MAP( clk => clk,
              reset => reset,
              dataIn_re => data_re,  -- sfix16_En15
              dataIn_im => data_im,  -- sfix16_En15
              validIn => valid,
              softReset => reset,
              dataOut_re => IFFT_HDL_Optimized_out1_re,  -- sfix20_En15
              dataOut_im => IFFT_HDL_Optimized_out1_im,  -- sfix20_En15
              validOut => IFFT_HDL_Optimized_out2
              );

  data_out_re <= IFFT_HDL_Optimized_out1_re;

  data_out_im <= IFFT_HDL_Optimized_out1_im;

  valid_out <= IFFT_HDL_Optimized_out2;

END rtl;

