function writeRunFile(rootPath,runFileName)

    % are we in single channel readout mode, and if so, on what channel?
    singleChannelReadoutOpt2 = lcaGet([rootPath 'singleChannelReadoutOpt2']);
    readoutChannelSelect = lcaGet([rootPath 'readoutChannelSelect']);

    %%
    %% Write config
    % reset config variable
    config0={};

    % Cryo config
    configvars={'VersionNumber', ...
                'waveformSelect', ...
                'waveformStart', ...
                'rfEnable', ...
                'iqSwapOut', ...
                'iqSwapIn', ...
                'refPhaseDelay', ...
                'toneScale', ...
                'feedbackEnable', ...
                'feedbackPolarity', ...
                'swapDfIQ', ...
                'statusChannelSelect', ...
                'feedbackGain', ...
                'feedbackLimit', ...
                'filterAlpha', ...
                'loopFilterOutputSel', ...
                'analysisScale', ...
                'synthesisScale', ...
                'decimation', ...
                'singleChannelReadout', ...
                'singleChannelReadoutOpt2', ...
                'readoutChannelSelect', ...
                'Q', ...
                'I', ...
                'dspCounter', ...
                'loopFilterOutput', ...
               };

    for cfgvar=configvars
        value=lcaGet([rootPath cfgvar{1}]);
        config0.(cfgvar{1})=value;
    end
    
    %
    % Some higher level FPGA config
    configvars={'FpgaVersion', ...
                'UpTimeCnt', ...
                'DeviceDna', ...
                'BuildStamp', ...
                };

    for cfgvar=configvars
        value=lcaGet(['mitch_epics:AMCc:FpgaTopLevel:AmcCarrierCore:AxiVersion:' cfgvar{1}]);
        config0.(cfgvar{1})=value;
    end

    % if single channel, save that config info
    if singleChannelReadoutOpt2==1
        singleChanPVprefix = [rootPath, 'CryoChannels:CryoChannel[', num2str(readoutChannelSelect), ']:'];
        config0.CryoChannel={};
        configvars={'etaMag', ...
                    'etaPhase', ...
                    'feedbackEnable', ...
                    'amplitudeScale', ...
                    'centerFrequency', ...
                    'loopFilterOutput', ...
                    'amplitudeReadback', ...
                    'frequencyError', ...
                   };
   
        for cfgvar=configvars
            value=lcaGet([singleChanPVprefix cfgvar{1}]);
            config0.CryoChannel.(cfgvar{1})=value;
        end
    end

    % save config
    save(runFileName,'-struct','config0');

    %% done writing config
end