`timescale 1 ns / 10 ps
// Generated from Simulink block 
module dspcore_stub (
  input [32-1:0] rampcnt,
  input [32-1:0] rddata0,
  input [32-1:0] rddata1,
  input [32-1:0] rddata2,
  input [32-1:0] rddata3,
  input [32-1:0] rddata4,
  input [32-1:0] rddata5,
  input [32-1:0] rddata6,
  input [32-1:0] rddata7,
  input [1-1:0] rst,
  input [1-1:0] selectramp,
  input [32-1:0] siggen0,
  input [32-1:0] siggen1,
  input [1-1:0] startramp,
  input [16-1:0] adc0,
  input [16-1:0] adc1,
  input dsp_clk,
  input dsp2x_clk,
  input dsp_axi_lite_clk,
  input dsp_axi_lite_aresetn,
  input [12-1:0] dsp_axi_lite_s_axi_awaddr,
  input dsp_axi_lite_s_axi_awvalid,
  input [32-1:0] dsp_axi_lite_s_axi_wdata,
  input [4-1:0] dsp_axi_lite_s_axi_wstrb,
  input dsp_axi_lite_s_axi_wvalid,
  input dsp_axi_lite_s_axi_bready,
  input [12-1:0] dsp_axi_lite_s_axi_araddr,
  input dsp_axi_lite_s_axi_arvalid,
  input dsp_axi_lite_s_axi_rready,
  output [32-1:0] debug0,
  output [32-1:0] debug1,
  output [2-1:0] debugvalids,
  output [7-1:0] rdaddr0,
  output [7-1:0] rdaddr1,
  output [7-1:0] rdaddr2,
  output [7-1:0] rdaddr3,
  output [7-1:0] rdaddr4,
  output [7-1:0] rdaddr5,
  output [7-1:0] rdaddr6,
  output [7-1:0] rdaddr7,
  output [1-1:0] siggenstart,
  output [7-1:0] wraddr0,
  output [7-1:0] wraddr1,
  output [7-1:0] wraddr2,
  output [7-1:0] wraddr3,
  output [7-1:0] wraddr4,
  output [7-1:0] wraddr5,
  output [7-1:0] wraddr6,
  output [7-1:0] wraddr7,
  output [32-1:0] wrdata0,
  output [32-1:0] wrdata1,
  output [32-1:0] wrdata2,
  output [32-1:0] wrdata3,
  output [32-1:0] wrdata4,
  output [32-1:0] wrdata5,
  output [32-1:0] wrdata6,
  output [32-1:0] wrdata7,
  output [16-1:0] dac0,
  output [16-1:0] dac1,
  output dsp_axi_lite_s_axi_awready,
  output dsp_axi_lite_s_axi_wready,
  output [2-1:0] dsp_axi_lite_s_axi_bresp,
  output dsp_axi_lite_s_axi_bvalid,
  output dsp_axi_lite_s_axi_arready,
  output [32-1:0] dsp_axi_lite_s_axi_rdata,
  output [2-1:0] dsp_axi_lite_s_axi_rresp,
  output dsp_axi_lite_s_axi_rvalid
);
  dspcore sysgen_dut (
    .rampcnt(rampcnt),
    .rddata0(rddata0),
    .rddata1(rddata1),
    .rddata2(rddata2),
    .rddata3(rddata3),
    .rddata4(rddata4),
    .rddata5(rddata5),
    .rddata6(rddata6),
    .rddata7(rddata7),
    .rst(rst),
    .selectramp(selectramp),
    .siggen0(siggen0),
    .siggen1(siggen1),
    .startramp(startramp),
    .adc0(adc0),
    .adc1(adc1),
    .dsp_clk(dsp_clk),
    .dsp2x_clk(dsp2x_clk),
    .dsp_axi_lite_clk(dsp_axi_lite_clk),
    .dsp_axi_lite_aresetn(dsp_axi_lite_aresetn),
    .dsp_axi_lite_s_axi_awaddr(dsp_axi_lite_s_axi_awaddr),
    .dsp_axi_lite_s_axi_awvalid(dsp_axi_lite_s_axi_awvalid),
    .dsp_axi_lite_s_axi_wdata(dsp_axi_lite_s_axi_wdata),
    .dsp_axi_lite_s_axi_wstrb(dsp_axi_lite_s_axi_wstrb),
    .dsp_axi_lite_s_axi_wvalid(dsp_axi_lite_s_axi_wvalid),
    .dsp_axi_lite_s_axi_bready(dsp_axi_lite_s_axi_bready),
    .dsp_axi_lite_s_axi_araddr(dsp_axi_lite_s_axi_araddr),
    .dsp_axi_lite_s_axi_arvalid(dsp_axi_lite_s_axi_arvalid),
    .dsp_axi_lite_s_axi_rready(dsp_axi_lite_s_axi_rready),
    .debug0(debug0),
    .debug1(debug1),
    .debugvalids(debugvalids),
    .rdaddr0(rdaddr0),
    .rdaddr1(rdaddr1),
    .rdaddr2(rdaddr2),
    .rdaddr3(rdaddr3),
    .rdaddr4(rdaddr4),
    .rdaddr5(rdaddr5),
    .rdaddr6(rdaddr6),
    .rdaddr7(rdaddr7),
    .siggenstart(siggenstart),
    .wraddr0(wraddr0),
    .wraddr1(wraddr1),
    .wraddr2(wraddr2),
    .wraddr3(wraddr3),
    .wraddr4(wraddr4),
    .wraddr5(wraddr5),
    .wraddr6(wraddr6),
    .wraddr7(wraddr7),
    .wrdata0(wrdata0),
    .wrdata1(wrdata1),
    .wrdata2(wrdata2),
    .wrdata3(wrdata3),
    .wrdata4(wrdata4),
    .wrdata5(wrdata5),
    .wrdata6(wrdata6),
    .wrdata7(wrdata7),
    .dac0(dac0),
    .dac1(dac1),
    .dsp_axi_lite_s_axi_awready(dsp_axi_lite_s_axi_awready),
    .dsp_axi_lite_s_axi_wready(dsp_axi_lite_s_axi_wready),
    .dsp_axi_lite_s_axi_bresp(dsp_axi_lite_s_axi_bresp),
    .dsp_axi_lite_s_axi_bvalid(dsp_axi_lite_s_axi_bvalid),
    .dsp_axi_lite_s_axi_arready(dsp_axi_lite_s_axi_arready),
    .dsp_axi_lite_s_axi_rdata(dsp_axi_lite_s_axi_rdata),
    .dsp_axi_lite_s_axi_rresp(dsp_axi_lite_s_axi_rresp),
    .dsp_axi_lite_s_axi_rvalid(dsp_axi_lite_s_axi_rvalid)
  );
endmodule
